# Generated by Django 6.0.3 on 2026-03-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50)),
                ('language', models.CharField(default='es', max_length=10)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ine_file_id', models.CharField(blank=True, max_length=200, null=True)),
                ('dates', models.CharField(blank=True, max_length=200, null=True)),
                ('nights', models.CharField(blank=True, max_length=50, null=True)),
                ('passengers', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
