# Generated by Django 6.0.3 on 2026-03-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, help_text='Unique token provided by @BotFather', max_length=255, null=True)),
                ('assistant_name', models.CharField(blank=True, help_text='Display name for your chatbot', max_length=255, null=True)),
                ('openai_api_key', models.CharField(blank=True, help_text='Your OpenAI secret key', max_length=255, null=True)),
                ('ai_model', models.CharField(default='gpt-3.5-turbo', help_text='The engine used for generation', max_length=100)),
                ('temperature', models.FloatField(default=0.7, help_text='Randomness factor')),
                ('max_tokens', models.IntegerField(default=1000, help_text='Tokens per answer')),
                ('conversation_tone', models.CharField(blank=True, help_text='General personality style', max_length=100, null=True)),
                ('emojis_enabled', models.BooleanField(default=True, help_text='Manage emojis')),
                ('welcome_message', models.TextField(blank=True, help_text='Sent immediately when a user starts the bot', null=True)),
                ('system_instructions', models.TextField(blank=True, help_text='Guidelines and persona traits the bot must follow', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
