# Generated by Django 6.0.3 on 2026-03-29 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_botsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='El usuario solo puede contener letras, números y guiones bajos.', regex='^[a-zA-Z0-9_]+$')])),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de correo electrónico inválido.', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')])),
                ('contrasena', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='passengers',
        ),
        migrations.AddField(
            model_name='prospect',
            name='passengers_adult',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='prospect',
            name='passengers_child',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='botsetting',
            name='assistant_name',
            field=models.CharField(blank=True, default='', help_text='Display name for your chatbot', max_length=255),
        ),
        migrations.AlterField(
            model_name='botsetting',
            name='bot_token',
            field=models.CharField(blank=True, default='', help_text='Unique token provided by @BotFather', max_length=255),
        ),
        migrations.AlterField(
            model_name='botsetting',
            name='conversation_tone',
            field=models.CharField(blank=True, default='', help_text='General personality style', max_length=100),
        ),
        migrations.AlterField(
            model_name='botsetting',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', help_text='Your OpenAI secret key', max_length=255),
        ),
        migrations.AlterField(
            model_name='botsetting',
            name='system_instructions',
            field=models.TextField(blank=True, default='', help_text='Guidelines and persona traits the bot must follow'),
        ),
        migrations.AlterField(
            model_name='botsetting',
            name='welcome_message',
            field=models.TextField(blank=True, default='', help_text='Sent immediately when a user starts the bot'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='dates',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, validators=[django.core.validators.RegexValidator(message='Formato de correo electrónico inválido.', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')]),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='ine_file_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='nights',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Phone format must be valid and numerical digits only.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='telegram_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
