# Generated by Django 6.0.3 on 2026-03-29 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_user_remove_prospect_passengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsetting',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_setting', to='chatbot.user'),
        ),
    ]
