# Generated by Django 6.0.3 on 2026-03-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_botsetting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsetting',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Enable or disable the bot for this user'),
        ),
    ]
