# Generated by Django 6.0.3 on 2026-05-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_botsetting_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsetting',
            name='is_active',
        ),
        migrations.AddField(
            model_name='prospect',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Destino de interés'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='ine_file',
            field=models.FileField(blank=True, null=True, upload_to='ines/', verbose_name='Archivo de Identificación'),
        ),
    ]
