# Generated by Django 6.0.5 on 2026-06-01 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_remove_botsetting_is_active_prospect_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='status',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
